### ISSUE TITLE
Create a form where user can create a new job profile

### ISSUE THREAD

**Issue by ChaitanyaBandikatla** [ChaitanyaBandikatla/easy-apply-chrome-extension#12]
As a user, after logging in, I should be able to create a job profile and fill in the details.

**Comment by ChaitanyaBandikatla** [comment]
![image](https://user-images.githubusercontent.com/5491923/92648979-56a85c80-f2b8-11ea-8905-e0264842c6cf.png)

**Comment by santoshp321** [comment]
![image](https://user-images.githubusercontent.com/10775930/92682132-875eb500-f2fd-11ea-9586-e9039c2a8a3e.png)

**Comment by santoshp321** [comment]
Need to implement the validations to the form inputs.

**Comment by santoshp321** [comment]
Have added validations and hints that give the user when validations fail.
